#!/bin/bash
echo "================================="
echo " Network Troubleshooting Toolkit "
echo "================================="


DOMAIN=$1
if [ $# -eq 0 ]
then
    echo "Usage: ./network-check.sh <domain>"
    exit 1
fi

check_dns() {

RESULT=$(dig $DOMAIN +short | head -1)

if [ -n "$RESULT" ]
then
    echo -e "[OK] DNS Resolution\nIP: $RESULT"
else
    echo -e "[FAIL] DNS Resolution\nNo DNS record found"
fi
}
check_dns

check_connectivity() {
ping -c 2 $DOMAIN > /dev/null 2>&1

if [ $? -eq 0 ]
then
    echo "[OK] Internet Connectivity"
else
    echo "[FAIL] Internet Connectivity"
fi
}
check_connectivity

check_latency(){
latency=$(ping -c 4 $DOMAIN | grep rtt | awk '{print $4}' | cut -d '/' -f 2)
echo "[OK] Latency: $latency ms"
}
check_latency
check_gateway() {
    gateway=$(ip route | grep default | awk '{print $3}')

    if [ -n "$gateway" ]
    then
        echo -e "[OK] Default Gateway Found\nGateway: $gateway"
    else
        echo "[FAIL] Default Gateway Missing"
    fi
}
check_gateway

check_public_ip(){
public_ip=$(curl -s ifconfig.me)

if [ -n "$public_ip" ]
then
echo -e "[OK] Public IP Found\nPublic IP: $public_ip"
else
echo "[FAIL] Unable to determine public IP"
fi
}
check_public_ip

check_ports() {
    port=$(ss -tulpn | tail -n +2 | awk '{print $5}' | awk -F ':' '{print $NF}' | sort -n | uniq)

    echo -e "open ports:\n$port"
}
check_ports
